### ISSUE TITLE
Separate virtual environment for each name

### ISSUE THREAD

**Issue by vpratz** [real-yfprojects/sphinx-polyversion#16]
Currently, at least for `Pip`, the name is not taken into account when creating/activating the virtual environment. This has the advantage that `venv` can be manually specified and is a fixed path.
In the case where we want to build groups of versions (eg. v1.*.*and v2.*.*) differently, and have a different environment for each sub-version, this is a bit cumbersome, as we have to spell out all versions to get different environments.
Changing this behavior is simple, by just changing [this line](https://github.com/real-yfprojects/sphinx-polyversion/blob/6b7a76320fb03b5e3a370bd3150f1856c83e0854/sphinx_polyversion/pyvenv.py#L365) from

```
super().__init__(path, name, venv, creator=creator)
```

to

```
super().__init__(path, name, Path(venv) / name, creator=creator)
```

(maybe with some additional escaping, depending on what `name` is exactly).

The harder part is to communicate well what is going on. As far as I understand it, the `Poetry` class also does not strictly respect the `venv` path, so maybe it would not be much of a problem?
If this is something worth implementing, what would be a good way to do it? Just a flag `venv_use_name` to activate the behavior?

**Comment by real-yfprojects** [comment]
Similar to what I wrote in https://github.com/real-yfprojects/sphinx-polyversion/issues/17#issuecomment-2556935662, for each revision a different directory is used to put source files and venv into. Thus there is no need to use the revision name when creating a venv. However the `Environment` interface defines and ensures that the `name` parameter is available to those Environment that need it. Imo this makes the code more general and extensible.

**Comment by vpratz** [comment]
I agree. Both issues come up for me because `Pip` currently does not create the venv in the temporary directory, but in the local one (as far as I can tell). I have made a longer comment in #17, maybe it's best to discuss it there.
