### ISSUE TITLE
max(tags or branches) does not reliably find newest revision

### ISSUE THREAD

**Issue by RAnders00** [real-yfprojects/sphinx-polyversion#2]
I copied your example code:

```python
def data(driver, rev, env):
    revisions = driver.targets
    branches, tags = refs_by_type(revisions)
    latest = max(tags or branches)
    return {
        "current": rev,
        "tags": tags,
        "branches": branches,
        "revisions": revisions,
        "latest": latest,
    }
```

However, after setting `MOCK = True`, it would always give me `v1.9.3`. I haven't taken the time into looking at *why*, but I've managed to fix this behaviour by modifying the call as follows:

```python
latest = max(tags + branches, key=lambda x: x.date)
```

Secondly, I think using `or` might also be a bug here, at least for dev environments with `MOCK = True`. I don't think it does the right thing. For example, if `MOCK = True`, it would prefer tags over branches, although the desired behaviour would be to redirect to the `local` tag from `index.html`.
<img width="403" alt="image" src="https://github.com/real-yfprojects/sphinx-polyversion/assets/1629196/741f8fd0-f91b-4ddc-8275-1897c786fb2b">

**Comment by real-yfprojects** [comment]
> However, after setting `MOCK = True`, it would always give me `v1.9.3`. I haven't taken the time into looking at _why_, but I've managed to fix this behaviour by modifying the call as follows:

I will have to look into this. But this is not intended. It should compare by date by default:

https://github.com/real-yfprojects/sphinx-polyversion/blob/3ffa372101b28e6e8d2586df9daa333068bb2ac4/sphinx_polyversion/git.py#L299-L301



> For example, if `MOCK = True`, it would prefer tags over branches, although the desired behaviour would be to redirect to the `local` tag

Good catch. I intentionally used `or` to prefer tags over branches in production. However for mocking it is less convenient.

**Comment by real-yfprojects** [comment]
I created #3 that fixes your issue. It changes the revision type of the local revision to `BRANCH` so that it will be considered by the `data` function.
