### ISSUE TITLE
Unable to find poetry virtual env running under CI

### ISSUE THREAD

**Issue by jamesrobson-secondmind** [real-yfprojects/sphinx-polyversion#6]
Hi, I've been experimenting with this tool and everything works locally but when run in our CI system polyversion is unable to find the poetry virtual env in the temp dir it has created. Running with `-vvv` shows output like:
```
[local] `poetry install`
[local] Installation output:
 Installing dependencies from lock file
<everything gets installed>

[local] Venv location: 
[local] Error locating venv:

subprocess.CalledProcessError: Command 'poetry env info --path' returned non-zero exit status 1.
```

Clearly it's something in the environment of the CI workers, do you have any insight into what that could be?
I can get this working if I change the section after https://github.com/real-yfprojects/sphinx-polyversion/blob/cbd7e184a58bf0ac351c43f0c96adef7989bcf8b/sphinx_polyversion/pyvenv.py#L279 to just return `venv_path` instead of asking poetry where the virtual env is, can you explain why the current approach was needed?

**Comment by jamesrobson-secondmind** [comment]
Part of the cause seems to be having a different versions of python used by the project and poetry. For some reason in the temp dir poetry would look for a virtual env created for its own python rather than the project python.
It's not clear why this is happening, but I have a simple fix for this situation

**Comment by real-yfprojects** [comment]
Thank you for your report! 

> Clearly it's something in the environment of the CI workers, do you have any insight into what that could be? I can get this working if I change the section after
> https://github.com/real-yfprojects/sphinx-polyversion/blob/cbd7e184a58bf0ac351c43f0c96adef7989bcf8b/sphinx_polyversion/pyvenv.py#L279
> to just return venv_path instead of asking poetry where the virtual env is, can you explain why the current approach was needed?

I assume you mean `self.venv = venv_path` rather than returning `venv_path`. In that case I wonder how this worked. We need to as poetry where the venv is located since poetry will place it in a subdirectory of `venv_path` using an undocumented naming scheme.

I will add some code commentary to explain this.

> It's not clear why this is happening, but I have a simple fix for this situation

So how did fix it?

**Comment by jamesrobson-secondmind** [comment]
> So how did fix it?

I changed the way poetry was installed to `pipx install --python <required python> poetry`, which changes the python version used to run poetry and gets it to look in the right place. This works for us as all our python projects are on the same version.
