### ISSUE TITLE
Release new version?

### ISSUE THREAD

**Issue by jamesrobson-secondmind** [real-yfprojects/sphinx-polyversion#7]
The current version on Pypi fails with new versions of python because it lacks https://github.com/real-yfprojects/sphinx-polyversion/commit/cb040a77cc4d167ce57139c82c67b77f6420afa7. Do you plan to push the latest code to Pypi?

**Comment by real-yfprojects** [comment]
Yes, I just released a new version. However it doesn't contain any new features.
